_BASE_: '../../base/market1501_transreid.yml'

MODEL:
  JPM: False

PEFT:
  METHOD: 'ssf'
  SSF:
    ENABLED: True
    BLOCKS: ()
    MERGE_ON_SAVE: False
    LR: 0.0
    FREEZE_BACKBONE: True
    OPTIMIZER_CASE: 1

OUTPUT_DIR: '../logs/catalogue_ssf_0_11_case1'
